# Importer les librairies, et fichiers .py auxiliaires

In [2]:
import numpy as np
from preprocess_data import *
from bayes_classifier import BayesClassifier
from complement_naive_bayes import train_cnb_with_tfidf, train_cnb
from ensemble_learning import train_ensemble
from xgboost_classifier import train_xgboost, train_xgboost_with_tfidf
from svc_classifier import *
from sgd_classifier import *
from sklearn.model_selection import StratifiedKFold

from save_output import save_output

In [3]:
data_preprocess = DataPreprocess()
X_train, y_train, X_test = data_preprocess.train, data_preprocess.label_train, data_preprocess.test

# Jalon 2)
# Naive Bayes Complement
K-Fold validation croisée stratifiée ($k = 5)$:
- α: Lissage du postérieur de Bayes
 
Prétraitement: TFIDF

In [7]:
complement_naive_bayes, tfidf_transformer = train_cnb_with_tfidf(X_train, y_train)
tfidf_test = tfidf_transformer.transform(X_test)
predictions = complement_naive_bayes.predict(tfidf_test)
save_output(predictions, "cnb", "random_search_50_iter", "tfidf")

Fitting 2 folds for each of 50 candidates, totalling 100 fits
[CV 1/2] END .....cnb__alpha=0.5619101782710437;, score=0.111 total time=   1.5s
[CV 2/2] END .....cnb__alpha=0.5619101782710437;, score=0.110 total time=   1.5s
[CV 1/2] END .....cnb__alpha=1.4261714596148742;, score=0.003 total time=   1.5s
[CV 2/2] END .....cnb__alpha=1.4261714596148742;, score=0.007 total time=   1.5s
[CV 1/2] END .....cnb__alpha=1.0980909127171077;, score=0.005 total time=   1.5s
[CV 2/2] END .....cnb__alpha=1.0980909127171077;, score=0.019 total time=   1.5s
[CV 1/2] END .....cnb__alpha=0.8980877262955549;, score=0.016 total time=   1.5s
[CV 2/2] END .....cnb__alpha=0.8980877262955549;, score=0.026 total time=   1.5s
[CV 1/2] END ....cnb__alpha=0.23412796066365477;, score=0.448 total time=   1.5s
[CV 2/2] END ....cnb__alpha=0.23412796066365477;, score=0.420 total time=   1.5s
[CV 1/2] END ....cnb__alpha=0.23409178050430396;, score=0.448 total time=   1.5s
[CV 2/2] END ....cnb__alpha=0.23409178050430396

Prétraitement: Sans prétraitement

In [8]:
complement_naive_bayes = train_cnb(X_train, y_train)
predictions = complement_naive_bayes.predict(X_test)
save_output(predictions, "cnb", "random_search_50_iter", "no_preprocessing")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END .....cnb__alpha=0.5619101782710437;, score=0.588 total time=   0.5s
[CV 2/2] END .....cnb__alpha=0.5619101782710437;, score=0.575 total time=   0.5s
Best Parameters: {'cnb__alpha': 0.5619101782710437}
Best F1 Score: 0.581482890607508
predictions saved in output/20241111/223336_cnb_random_search_50_iter_no_preprocessing.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/204747_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/154833_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/162028_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/200251_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/162135_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/162421_cnb_random_search_50_iter_no_preprocessing.csv
	 output/20241111/154327_cnb_random_search_50_iter_no_preprocessing.csv
	 out

Prétraitement: TFIDF, réduction par arbre, stopwords retirés

In [4]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
X_train, sorted_indices_features = tree_based_dimensionality_reduction(data_preprocess.train, data_preprocess.label_train)
X_test = data_preprocess.test[:, sorted_indices_features]
complement_naive_bayes, tfidf_transformer = train_cnb_with_tfidf(X_train, data_preprocess.label_train)
tfidf_test = tfidf_transformer.transform(X_test)
predictions = complement_naive_bayes.predict(tfidf_test)
save_output(predictions, "cnb", "random_search_50_iter", "tree_reduction_stopwords_tfidf")

Fitting 2 folds for each of 50 candidates, totalling 100 fits
[CV 1/2] END .....cnb__alpha=0.5619101782710437;, score=0.572 total time=   0.1s
[CV 2/2] END .....cnb__alpha=0.5619101782710437;, score=0.556 total time=   0.1s
[CV 1/2] END .....cnb__alpha=1.4261714596148742;, score=0.568 total time=   0.1s
[CV 2/2] END .....cnb__alpha=1.4261714596148742;, score=0.544 total time=   0.1s
[CV 1/2] END .....cnb__alpha=1.0980909127171077;, score=0.572 total time=   0.1s
[CV 2/2] END .....cnb__alpha=1.0980909127171077;, score=0.553 total time=   0.1s
[CV 1/2] END .....cnb__alpha=0.8980877262955549;, score=0.571 total time=   0.1s
[CV 2/2] END .....cnb__alpha=0.8980877262955549;, score=0.554 total time=   0.1s
[CV 1/2] END ....cnb__alpha=0.23412796066365477;, score=0.562 total time=   0.1s
[CV 2/2] END ....cnb__alpha=0.23412796066365477;, score=0.551 total time=   0.1s
[CV 1/2] END ....cnb__alpha=0.23409178050430396;, score=0.562 total time=   0.1s
[CV 2/2] END ....cnb__alpha=0.23409178050430396

Prétraitement: TFIDF, réduction par arbre, stopwords retirés, suréchantillonnage SMOTE

In [5]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
X_train, sorted_indices_features = tree_based_dimensionality_reduction(data_preprocess.train, data_preprocess.label_train)
X_test = data_preprocess.test[:, sorted_indices_features]
X_train, y_train = smote_oversampling(X_train, data_preprocess.label_train)

complement_naive_bayes = train_cnb(X_train, y_train)
tfidf_test = tfidf_transformer.transform(X_test)
predictions = complement_naive_bayes.predict(tfidf_test)

save_output(predictions, "cnb", "random_search_50_iter", "tree_reduction_stopwords_tfidf_smote")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END .....cnb__alpha=0.5619101782710437;, score=0.635 total time=   0.0s
[CV 2/2] END .....cnb__alpha=0.5619101782710437;, score=0.655 total time=   0.0s
Best Parameters: {'cnb__alpha': 0.5619101782710437}
Best F1 Score: 0.6450953216247627
predictions saved in output/20241111/223814_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/200509_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/204814_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/215844_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/223408_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
Number of 0: 1419
Number of 1: 937
Ratio of 1: 0.3977079796264856
Number of differences with bayes classifier submission

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [6]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

complement_naive_bayes = train_cnb(X_train, y_train)
tfidf_test = tfidf_transformer.transform(X_test)
predictions = complement_naive_bayes.predict(tfidf_test)

save_output(predictions, "cnb", "random_search_50_iter", "stopwords_cum-sum_undersampled")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END .....cnb__alpha=0.5619101782710437;, score=0.635 total time=   0.0s
[CV 2/2] END .....cnb__alpha=0.5619101782710437;, score=0.655 total time=   0.0s
Best Parameters: {'cnb__alpha': 0.5619101782710437}
Best F1 Score: 0.6450953216247627
predictions saved in output/20241111/223815_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/200509_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/204814_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/223814_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/215844_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
	 output/20241111/223408_cnb_random_search_50_iter_tree_reduction_stopwords_tfidf_smote.csv
Number of 0: 1419
Number of 

# SVC
Grid Search, K-Fold validation croisée stratifiée ($k = 5)$, avec hyperparamètres:
- $\gamma$ : Coefficient du Noyau RBF
- $C$ : Terme de régularization pour la pénalité euclidienne.

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [7]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

best_params_, best_score_ = train_svc(X_train_undersampled, y_train_undersampled)
print(best_params_, best_score_)
svc = SVC(kernel='rbf', C=best_params_['C'], gamma=best_params_['gamma'])
svc.fit(X_train_undersampled, y_train_undersampled)
y_pred = svc.predict(data_preprocess.test)
params = f"C={best_params_['C']}, gamma={best_params_['gamma']}"
save_output(y_pred, "svm", params, "stopwords_cum-sum_undersampled")

{'gamma': array([0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01 , 0.011,
       0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018, 0.019]), 'C': array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54])}
Fitting 1 folds for each of 170 candidates, totalling 170 fits
[CV 1/1] END .................C=45, gamma=0.003;, score=0.635 total time=   0.5s
[CV 1/1] END .................C=45, gamma=0.004;, score=0.646 total time=   0.2s
[CV 1/1] END .................C=45, gamma=0.005;, score=0.651 total time=   0.2s
[CV 1/1] END .................C=45, gamma=0.006;, score=0.651 total time=   0.2s
[CV 1/1] END .................C=45, gamma=0.007;, score=0.650 total time=   0.2s
[CV 1/1] END .................C=45, gamma=0.008;, score=0.643 total time=   0.2s
[CV 1/1] END ..C=45, gamma=0.009000000000000001;, score=0.635 total time=   0.2s
[CV 1/1] END ..................C=45, gamma=0.01;, score=0.631 total time=   0.2s
[CV 1/1] END .................C=45, gamma=0.011;, score=0.620 total time=   0.2s
[CV 1/1] 

/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


{'C': 45, 'gamma': 0.006} 0.6510574018126888
predictions saved in output/20241111/224209_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/163020_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
	 output/20241111/200600_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
	 output/20241111/162517_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
	 output/20241111/215926_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
	 output/20241111/204856_svm_C=45, gamma=0.006_stopwords_cum-sum_undersampled.csv
Number of 0: 1683
Number of 1: 673
Ratio of 1: 0.28565365025466893
Number of differences with bayes classifier submission: 396
Ratio of 1 in bayes submission: 0.29499151103565363


# SGDClassifier
Random Search, K-Fold validation croisée stratifiée ($k = 5)$, avec hyperparamètres:
- loss: ModifiedHuber 
- penalty: ElaticNet 
- l1_ratio: Porportion de la perte d'ElasticNet qui est l1.
- $\alpha$: Poids attribué au terme de régularisation. Une plus grande valeur favorise que certains coefficients soient annulés (par l1) ou fortement adoucis (par l2) quand la pénalité est ElaticNet. 

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [8]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

best_sgd = train_sgd(X_train_undersampled, y_train_undersampled)
predictions_voter = best_sgd.predict(data_preprocess.test)
save_output(predictions_voter, "sgd", "random_search_15_iter", "stopwords_undersampling_cumulative_sum")

Fitting 2 folds for each of 15 candidates, totalling 30 fits
[CV 1/2] END model__alpha=0.027825594022071243, model__l1_ratio=0.667;, score=0.562 total time=   1.3s
[CV 2/2] END model__alpha=0.027825594022071243, model__l1_ratio=0.667;, score=0.524 total time=   1.4s
[CV 1/2] END model__alpha=0.5994842503189409, model__l1_ratio=0.667;, score=0.000 total time=   0.4s
[CV 2/2] END model__alpha=0.5994842503189409, model__l1_ratio=0.667;, score=0.000 total time=   0.4s
[CV 1/2] END model__alpha=0.01, model__l1_ratio=0.223;, score=0.612 total time=   2.0s
[CV 2/2] END model__alpha=0.01, model__l1_ratio=0.223;, score=0.609 total time=   2.1s
[CV 1/2] END model__alpha=0.1291549665014884, model__l1_ratio=0.556;, score=0.198 total time=   0.7s
[CV 2/2] END model__alpha=0.1291549665014884, model__l1_ratio=0.556;, score=0.198 total time=   1.0s
[CV 1/2] END model__alpha=0.3593813663804626, model__l1_ratio=0.556;, score=0.000 total time=   0.4s
[CV 2/2] END model__alpha=0.3593813663804626, model__l

# XGBoost
Random Search, K-Fold validation croisée stratifiée ($k = 5)$, avec hyperparamètres:
- Learning rate: Taille du pas lors de la descente de critère sur la perte (gain de subdivision) 
- Nombre d'estimateurs (n_estimators): Nombre d'arbres de décision
- Profondeur maximale (max_depth): Profondeur maximale de chaque arbre (nombre de branchements max)
- sous-échantillon (subsample):  Proportion de données utilisées pour produire chaque arbre.

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [10]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

xgboost_classifier = train_xgboost(X_train_undersampled, y_train_undersampled)
predictions = xgboost_classifier.predict(data_preprocess.test)
save_output(predictions, "xgboost", "random_search_15_iter", "stopwords_undersampling_cumulative_sum")

Fitting 2 folds for each of 15 candidates, totalling 30 fits
[CV 1/2] END model__learning_rate=0.0849080237694725, model__max_depth=3, model__n_estimators=400, model__subsample=0.892797576724562;, score=0.635 total time=   2.4s
[CV 2/2] END model__learning_rate=0.0849080237694725, model__max_depth=3, model__n_estimators=400, model__subsample=0.892797576724562;, score=0.618 total time=   2.4s
[CV 1/2] END model__learning_rate=0.12973169683940733, model__max_depth=7, model__n_estimators=300, model__subsample=0.662397808134481;, score=0.648 total time=   2.8s
[CV 2/2] END model__learning_rate=0.12973169683940733, model__max_depth=7, model__n_estimators=300, model__subsample=0.662397808134481;, score=0.642 total time=   3.0s
[CV 1/2] END model__learning_rate=0.021616722433639893, model__max_depth=10, model__n_estimators=200, model__subsample=0.8404460046972835;, score=0.615 total time=   2.9s
[CV 2/2] END model__learning_rate=0.021616722433639893, model__max_depth=10, model__n_estimators=2

# Apprentissage par ensembles: CNB, XGBoost, Logistic Regression

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [11]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = []
model_names = ['ComplementNB', 'XGBoost', 'LogisticRegression']
# Validation croisée du voteur
for train_index, test_index in kf.split(X_train_undersampled, y_train_undersampled):
    # Split données
    X_train, X_test = X_train_undersampled[train_index], X_train_undersampled[test_index]
    y_train, y_test = y_train_undersampled[train_index], y_train_undersampled[test_index]
    best_ensemble_model = train_ensemble(X_train, y_train, model_names)    
    y_pred = best_ensemble_model.predict(X_test)
    score = f1_score(y_test, y_pred)
    scores.append(score)

mean_score = np.mean(scores)
print("Score F1 de validation du voteur: ", mean_score)

best_ensemble_model = train_ensemble(X_train_undersampled, y_train_undersampled, model_names)
predictions_voter = best_ensemble_model.predict(data_preprocess.test)
save_output(predictions_voter, "ensemble_cnb_xgboost_logreg", "random_search_15_iter", "stopwords_undersampling_cumulative_sum")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.689 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.678 total time=   0.1s
Best F1 for ComplementNB: 0.6837390151836877
Confusion Matrix - Fold 1:
[[1028  397]
 [ 227  692]]

Confusion Matrix - Fold 2:
[[1011  414]
 [ 235  684]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:48:55] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.625 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:48:56] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.622 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:48:57] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6235194453044464


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:00] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:01] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1176  249]
 [ 388  531]]

Confusion Matrix - Fold 2:
[[1152  273]
 [ 381  538]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.614 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.607 total time=   0.1s
Best F1 for LogisticRegression: 0.610803580621378
Confusion Matrix - Fold 1:
[[1063  362]
 [ 351  568]]

Confusion Matrix - Fold 2:
[[1071  354]
 [ 364  555]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:03] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.676 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.687 total time=   0.1s
Best F1 for ComplementNB: 0.6813773125608569
Confusion Matrix - Fold 1:
[[984 441]
 [225 694]]

Confusion Matrix - Fold 2:
[[1031  394]
 [ 232  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:06] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.626 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:07] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.614 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:08] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6201772694734053


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:10] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:12] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1163  262]
 [ 381  538]]

Confusion Matrix - Fold 2:
[[1142  283]
 [ 386  533]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.609 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.571 total time=   0.1s
Best F1 for LogisticRegression: 0.5900256346043851
Confusion Matrix - Fold 1:
[[1052  373]
 [ 353  566]]

Confusion Matrix - Fold 2:
[[1058  367]
 [ 405  514]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:14] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.701 total time=   0.1s
Best F1 for ComplementNB: 0.6911274834395083
Confusion Matrix - Fold 1:
[[1019  406]
 [ 234  685]]

Confusion Matrix - Fold 2:
[[1070  355]
 [ 232  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:16] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.616 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:18] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:19] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6141594581826888


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:21] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:23] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1139  286]
 [ 383  536]]

Confusion Matrix - Fold 2:
[[1164  261]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.611 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.576 total time=   0.1s
Best F1 for LogisticRegression: 0.5936256215233078
Confusion Matrix - Fold 1:
[[1049  376]
 [ 349  570]]

Confusion Matrix - Fold 2:
[[1051  374]
 [ 396  523]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:24] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.695 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.685 total time=   0.1s
Best F1 for ComplementNB: 0.6897205813831147
Confusion Matrix - Fold 1:
[[1048  376]
 [ 230  690]]

Confusion Matrix - Fold 2:
[[1022  403]
 [ 231  688]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:27] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.627 total time=   1.5s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:29] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:30] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6198774367553173


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:32] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:34] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1161  263]
 [ 380  540]]

Confusion Matrix - Fold 2:
[[1165  260]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.614 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.590 total time=   0.1s
Best F1 for LogisticRegression: 0.6021585839517554
Confusion Matrix - Fold 1:
[[1065  359]
 [ 354  566]]

Confusion Matrix - Fold 2:
[[1062  363]
 [ 382  537]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:36] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.693 total time=   0.1s
Best F1 for ComplementNB: 0.6876064518070476
Confusion Matrix - Fold 1:
[[1087  337]
 [ 269  651]]

Confusion Matrix - Fold 2:
[[978 447]
 [195 724]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:39] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.612 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:40] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.620 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:41] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6160634973297516


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:43] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:44] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1181  243]
 [ 407  513]]

Confusion Matrix - Fold 2:
[[1113  312]
 [ 366  553]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.601 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.601 total time=   0.1s
Best F1 for LogisticRegression: 0.6009757736912547
Confusion Matrix - Fold 1:
[[1076  348]
 [ 375  545]]

Confusion Matrix - Fold 2:
[[1035  390]
 [ 357  562]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:46] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Score F1 de validation du voteur:  0.6819091690445443
Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.694 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.685 total time=   0.1s
Best F1 for ComplementNB: 0.6895566521985158
Confusion Matrix - Fold 1:
[[1329  452]
 [ 298  851]]

Confusion Matrix - Fold 2:
[[1279  502]
 [ 289  860]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:49] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.630 total time=   1.6s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:51] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.635 total time=   1.5s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:52] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6321269577091664


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:55] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:57] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1500  281]
 [ 492  657]]

Confusion Matrix - Fold 2:
[[1452  329]
 [ 462  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.581 total time=   0.1s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.600 total time=   0.1s
Best F1 for LogisticRegression: 0.5907665275877441
Confusion Matrix - Fold 1:
[[1332  449]
 [ 494  655]]

Confusion Matrix - Fold 2:
[[1304  477]
 [ 452  697]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:49:59] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


predictions saved in output/20241111/225002_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling_cumulative_sum.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/155220_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling_cumulative_sum.csv
	 output/20241111/205843_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling_cumulative_sum.csv
Number of 0: 1569
Number of 1: 787
Ratio of 1: 0.3340407470288625
Number of differences with bayes classifier submission: 250
Ratio of 1 in bayes submission: 0.29499151103565363


Prétraitement: Retirer stopwords, sous-échantillonage aléatoire

In [13]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = []
model_names = ['ComplementNB', 'XGBoost', 'LogisticRegression']
# Validation croisée du voteur
for train_index, test_index in kf.split(X_train_undersampled, y_train_undersampled):
    # Split données
    X_train, X_test = X_train_undersampled[train_index], X_train_undersampled[test_index]
    y_train, y_test = y_train_undersampled[train_index], y_train_undersampled[test_index]
    best_ensemble_model = train_ensemble(X_train, y_train, model_names)    
    y_pred = best_ensemble_model.predict(X_test)
    score = f1_score(y_test, y_pred)
    scores.append(score)

mean_score = np.mean(scores)
print("Score F1 de validation du voteur: ", mean_score)

best_ensemble_model = train_ensemble(X_train_undersampled, y_train_undersampled, model_names)
predictions_voter = best_ensemble_model.predict(data_preprocess.test)
save_output(predictions_voter, "ensemble_cnb_xgboost_logreg", "random_search_15_iter", "stopwords_undersampling")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.2s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.677 total time=   0.2s
Best F1 for ComplementNB: 0.6793106248810417
Confusion Matrix - Fold 1:
[[1023  402]
 [ 236  683]]

Confusion Matrix - Fold 2:
[[1019  406]
 [ 241  678]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:07] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.625 total time=   3.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:11] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.622 total time=   3.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:14] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6235194453044464


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:20] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:24] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1176  249]
 [ 388  531]]

Confusion Matrix - Fold 2:
[[1152  273]
 [ 381  538]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.602 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.601 total time=   0.3s
Best F1 for LogisticRegression: 0.6013638867795298
Confusion Matrix - Fold 1:
[[1061  364]
 [ 367  552]]

Confusion Matrix - Fold 2:
[[1064  361]
 [ 368  551]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:29] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.669 total time=   0.2s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.2s
Best F1 for ComplementNB: 0.6756226635656272
Confusion Matrix - Fold 1:
[[980 445]
 [233 686]]

Confusion Matrix - Fold 2:
[[1024  401]
 [ 236  683]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:36] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.626 total time=   3.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:40] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.614 total time=   3.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:43] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6201772694734053


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:49] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:52] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1163  262]
 [ 381  538]]

Confusion Matrix - Fold 2:
[[1142  283]
 [ 386  533]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.614 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.573 total time=   0.3s
Best F1 for LogisticRegression: 0.5935799618451705
Confusion Matrix - Fold 1:
[[1065  360]
 [ 352  567]]

Confusion Matrix - Fold 2:
[[1061  364]
 [ 404  515]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:53:57] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.676 total time=   0.2s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.691 total time=   0.2s
Best F1 for ComplementNB: 0.6835443230944545
Confusion Matrix - Fold 1:
[[1017  408]
 [ 241  678]]

Confusion Matrix - Fold 2:
[[1059  366]
 [ 241  678]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:05] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.616 total time=   3.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:08] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   3.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:12] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6141594581826888


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:18] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:21] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1139  286]
 [ 383  536]]

Confusion Matrix - Fold 2:
[[1164  261]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.599 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.580 total time=   0.3s
Best F1 for LogisticRegression: 0.5893871166659146
Confusion Matrix - Fold 1:
[[1048  377]
 [ 365  554]]

Confusion Matrix - Fold 2:
[[1069  356]
 [ 398  521]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:27] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.691 total time=   0.2s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.679 total time=   0.2s
Best F1 for ComplementNB: 0.6850886095300368
Confusion Matrix - Fold 1:
[[1042  382]
 [ 233  687]]

Confusion Matrix - Fold 2:
[[1028  397]
 [ 242  677]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:34] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.627 total time=   3.5s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:38] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   3.6s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:42] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6198774367553173


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:48] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:52] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1161  263]
 [ 380  540]]

Confusion Matrix - Fold 2:
[[1165  260]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.613 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.595 total time=   0.3s
Best F1 for LogisticRegression: 0.6042498483959207
Confusion Matrix - Fold 1:
[[1080  344]
 [ 361  559]]

Confusion Matrix - Fold 2:
[[1078  347]
 [ 383  536]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:54:57] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.683 total time=   0.2s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.695 total time=   0.2s
Best F1 for ComplementNB: 0.6890146307469143
Confusion Matrix - Fold 1:
[[1090  334]
 [ 269  651]]

Confusion Matrix - Fold 2:
[[987 438]
 [197 722]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:05] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.612 total time=   3.6s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:08] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.620 total time=   3.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:12] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6160634973297516


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:18] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:21] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1181  243]
 [ 407  513]]

Confusion Matrix - Fold 2:
[[1113  312]
 [ 366  553]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.598 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.599 total time=   0.3s
Best F1 for LogisticRegression: 0.5981975112792124
Confusion Matrix - Fold 1:
[[1077  347]
 [ 381  539]]

Confusion Matrix - Fold 2:
[[1031  394]
 [ 358  561]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:26] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Score F1 de validation du voteur:  0.6785479295427365
Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.687 total time=   0.3s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.683 total time=   0.3s
Best F1 for ComplementNB: 0.6849461126344383
Confusion Matrix - Fold 1:
[[1298  483]
 [ 296  853]]

Confusion Matrix - Fold 2:
[[1275  506]
 [ 290  859]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:35] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.630 total time=   4.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:39] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.635 total time=   4.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:43] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6321269577091664


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:50] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:55:54] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1500  281]
 [ 492  657]]

Confusion Matrix - Fold 2:
[[1452  329]
 [ 462  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.587 total time=   0.3s
[CV 2/2] END model__C=5.588135039273247, model__penalty=l1, model__solver=liblinear;, score=0.605 total time=   0.3s
Best F1 for LogisticRegression: 0.5961926125858565
Confusion Matrix - Fold 1:
[[1350  431]
 [ 492  657]]

Confusion Matrix - Fold 2:
[[1306  475]
 [ 447  702]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:01] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


predictions saved in output/20241111/225608_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 output/20241111/210232_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling.csv
	 output/20241111/225304_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling.csv
	 output/20241111/155258_ensemble_cnb_xgboost_logreg_random_search_15_iter_stopwords_undersampling_cumulative_sum.csv
Number of 0: 1569
Number of 1: 787
Ratio of 1: 0.3340407470288625
Number of differences with bayes classifier submission: 236
Ratio of 1 in bayes submission: 0.29499151103565363


# Apprentissage par ensembles: Complement Naive Bayes, XGBoost, SVC, SGD

Prétraitement: Retirer stopwords, Réduction par somme cumulative, sous-échantillonage aléatoire

In [14]:
data_preprocess = DataPreprocess()
data_preprocess.remove_stopwords()
data_preprocess.remove_cum_sum()
X_train_undersampled, y_train_undersampled = random_undersampling(data_preprocess.train, data_preprocess.label_train)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = []
model_names = ['ComplementNB', 'XGBoost', 'SVC', 'SGD']
# Validation croisée du voteur
for train_index, test_index in kf.split(X_train_undersampled, y_train_undersampled):
    # Split données
    X_train, X_test = X_train_undersampled[train_index], X_train_undersampled[test_index]
    y_train, y_test = y_train_undersampled[train_index], y_train_undersampled[test_index]
    best_ensemble_model = train_ensemble(X_train, y_train, model_names)    
    y_pred = best_ensemble_model.predict(X_test)
    score = f1_score(y_test, y_pred)
    scores.append(score)

mean_score = np.mean(scores)
print("Score F1 de validation du voteur: ", mean_score)

best_ensemble_model = train_ensemble(X_train_undersampled, y_train_undersampled, model_names)
predictions_voter = best_ensemble_model.predict(data_preprocess.test)
save_output(predictions_voter, "ensemble_cnb_xgboost_svc_sgd", "random_search_15_iter", "stopwords_undersampling_cumulative_sum")

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.689 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.678 total time=   0.1s
Best F1 for ComplementNB: 0.6837390151836877
Confusion Matrix - Fold 1:
[[1028  397]
 [ 227  692]]

Confusion Matrix - Fold 2:
[[1011  414]
 [ 235  684]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:10] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.625 total time=   1.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:12] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.622 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:13] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6235194453044464


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:15] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [22:56:17] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1176  249]
 [ 388  531]]

Confusion Matrix - Fold 2:
[[1152  273]
 [ 381  538]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.468 total time= 1.3min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.494 total time= 1.3min
Best F1 for SVC: 0.4809231232587908
Confusion Matrix - Fold 1:
[[1273  152]
 [ 592  327]]

Confusion Matrix - Fold 2:
[[1271  154]
 [ 567  352]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.412 total time=   1.1s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.442 total time=   1.0s
Best F1 for SGDClassifier: 0.42702953034760815
Confusion Matrix - Fold 1:
[[1211  214]
 [ 557  362]]

Confusion Matrix - Fold 2:
[[1282  143]
 [ 616  303]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:05:50] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.676 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.687 total time=   0.1s
Best F1 for ComplementNB: 0.6813773125608569
Confusion Matrix - Fold 1:
[[984 441]
 [225 694]]

Confusion Matrix - Fold 2:
[[1031  394]
 [ 232  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:10:22] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.626 total time=   1.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:10:23] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.614 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:10:25] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6201772694734053


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:10:27] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:10:28] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1163  262]
 [ 381  538]]

Confusion Matrix - Fold 2:
[[1142  283]
 [ 386  533]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.479 total time= 1.3min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.497 total time= 1.3min
Best F1 for SVC: 0.4876989473758886
Confusion Matrix - Fold 1:
[[1257  168]
 [ 577  342]]

Confusion Matrix - Fold 2:
[[1306  119]
 [ 576  343]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.447 total time=   1.1s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.424 total time=   1.0s
Best F1 for SGDClassifier: 0.43550776583034645
Confusion Matrix - Fold 1:
[[1266  159]
 [ 613  306]]

Confusion Matrix - Fold 2:
[[1305  120]
 [ 685  234]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:19:58] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.701 total time=   0.1s
Best F1 for ComplementNB: 0.6911274834395083
Confusion Matrix - Fold 1:
[[1019  406]
 [ 234  685]]

Confusion Matrix - Fold 2:
[[1070  355]
 [ 232  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:24:31] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.616 total time=   1.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:24:32] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   1.2s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:24:33] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6141594581826888


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:24:36] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:24:37] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1139  286]
 [ 383  536]]

Confusion Matrix - Fold 2:
[[1164  261]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.500 total time= 1.3min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.514 total time= 1.3min
Best F1 for SVC: 0.5071032571032571
Confusion Matrix - Fold 1:
[[1264  161]
 [ 559  360]]

Confusion Matrix - Fold 2:
[[1272  153]
 [ 548  371]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.424 total time=   0.9s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.475 total time=   1.0s
Best F1 for SGDClassifier: 0.4494563960212815
Confusion Matrix - Fold 1:
[[1262  163]
 [ 632  287]]

Confusion Matrix - Fold 2:
[[1239  186]
 [ 590  329]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:34:08] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.695 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.685 total time=   0.1s
Best F1 for ComplementNB: 0.6897205813831147
Confusion Matrix - Fold 1:
[[1048  376]
 [ 230  690]]

Confusion Matrix - Fold 2:
[[1022  403]
 [ 231  688]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:38:42] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.627 total time=   1.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:38:44] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.613 total time=   1.4s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:38:45] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6198774367553173


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:38:47] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:38:48] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1161  263]
 [ 380  540]]

Confusion Matrix - Fold 2:
[[1165  260]
 [ 398  521]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.524 total time= 1.3min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.476 total time= 1.3min
Best F1 for SVC: 0.5001194512909096
Confusion Matrix - Fold 1:
[[1273  151]
 [ 540  380]]

Confusion Matrix - Fold 2:
[[1276  149]
 [ 585  334]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.428 total time=   1.4s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.407 total time=   0.6s
Best F1 for SGDClassifier: 0.4174521688063908
Confusion Matrix - Fold 1:
[[1294  130]
 [ 641  279]]

Confusion Matrix - Fold 2:
[[1266  159]
 [ 621  298]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:48:21] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.682 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.693 total time=   0.1s
Best F1 for ComplementNB: 0.6876064518070476
Confusion Matrix - Fold 1:
[[1087  337]
 [ 269  651]]

Confusion Matrix - Fold 2:
[[978 447]
 [195 724]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:52:56] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.612 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:52:57] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.620 total time=   1.3s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:52:58] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6160634973297516


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:53:01] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [23:53:02] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1181  243]
 [ 407  513]]

Confusion Matrix - Fold 2:
[[1113  312]
 [ 366  553]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.487 total time= 1.3min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.511 total time= 1.3min
Best F1 for SVC: 0.499041769041769
Confusion Matrix - Fold 1:
[[1304  120]
 [ 585  335]]

Confusion Matrix - Fold 2:
[[1242  183]
 [ 541  378]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.417 total time=   0.7s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.441 total time=   0.8s
Best F1 for SGDClassifier: 0.4293307739813712
Confusion Matrix - Fold 1:
[[1247  177]
 [ 585  335]]

Confusion Matrix - Fold 2:
[[1230  195]
 [ 560  359]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:02:32] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Score F1 de validation du voteur:  0.6895449158756004
Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__alpha=0.3851694527491273;, score=0.694 total time=   0.1s
[CV 2/2] END ...model__alpha=0.3851694527491273;, score=0.685 total time=   0.1s
Best F1 for ComplementNB: 0.6895566521985158
Confusion Matrix - Fold 1:
[[1329  452]
 [ 298  851]]

Confusion Matrix - Fold 2:
[[1279  502]
 [ 289  860]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:07:04] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 1/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.630 total time=   1.6s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:07:06] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[CV 2/2] END model__learning_rate=0.11976270078546496, model__max_depth=5, model__n_estimators=200, model__subsample=0.8411053504286575;, score=0.635 total time=   1.6s


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:07:08] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best F1 for XGBClassifier: 0.6321269577091664


/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:07:10] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:07:12] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Confusion Matrix - Fold 1:
[[1500  281]
 [ 492  657]]

Confusion Matrix - Fold 2:
[[1452  329]
 [ 462  687]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END ...model__C=47, model__gamma=0.016;, score=0.507 total time= 2.1min
[CV 2/2] END ...model__C=47, model__gamma=0.016;, score=0.522 total time= 2.1min
Best F1 for SVC: 0.5144048932843956
Confusion Matrix - Fold 1:
[[1630  151]
 [ 708  441]]

Confusion Matrix - Fold 2:
[[1549  232]
 [ 661  488]]

Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.441 total time=   0.8s
[CV 2/2] END model__alpha=0.0774263682681127, model__l1_ratio=0.445;, score=0.420 total time=   1.1s
Best F1 for SGDClassifier: 0.43032938318482
Confusion Matrix - Fold 1:
[[1599  182]
 [ 800  349]]

Confusion Matrix - Fold 2:
[[1553  228]
 [ 764  385]]



/home/ggenois/anaconda3/envs/rapids-24.08/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [00:22:04] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1722516643542/work/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


predictions saved in output/20241112/002919_ensemble_cnb_xgboost_svc_sgd_random_search_15_iter_stopwords_undersampling_cumulative_sum.csv
already same predictions saved in submissions? None
already same predictions saved in output?
	 None
Number of 0: 1570
Number of 1: 786
Ratio of 1: 0.333616298811545
Number of differences with bayes classifier submission: 171
Ratio of 1 in bayes submission: 0.29499151103565363
